### ISSUE TITLE
As an instructor, I should the ability to extract data in a CSV format

### ISSUE THREAD

**Issue by milindvishnoi** [utmgdsc/QuickTA#25]

**Comment by Isukani** [comment]
Endpoints completed:

POST /api/researcher/average-ratings-csv
POST /api/researcher/reported-conversations-csv
POST /api/researcher/reported-chatlogs-csv
POST /api/researcher/avg-response-rate-csv
POST /api/researcher/avg-comfortability-ratings-csv
